language: go

go:
  - 1.7.x
  - 1.x

install: make setup
script:
  # check compilation on supported targets
  - GOARCH=linux   GOOS=amd64 make binaries
  - GOARCH=windows GOOS=amd64 make binaries
  - GOARCH=darwin  GOOS=amd64 make binaries
  - GOARCH=linux   GOOS=arm make binaries
  - GOARCH=linux   GOOS=386 make binaries
  # run tests
  - make ci
