language: go

go:
  - 1.7.x
  - 1.x

install: make setup
script:
  # check compilation on supported targets
  - GOOS=linux   GOARCH=amd64 make binaries
  - GOOS=windows GOARCH=amd64 make binaries
  - GOOS=darwin  GOARCH=amd64 make binaries
  - GOOS=linux   GOARCH=arm   make binaries
  - GOOS=linux   GOARCH=386   make binaries
  # run tests
  - make ci
